-- AlterTable
ALTER TABLE "FinancialTransaction" ADD COLUMN     "dueDate" TIMESTAMP(3),
ADD COLUMN     "paidAt" TIMESTAMP(3),
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'PAID';

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "costPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "freight" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "otherCosts" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "profitMargin" DOUBLE PRECISION NOT NULL DEFAULT 0;
